### ISSUE TITLE
missing Couchbase MacOS M1-M2 ARM64 images support

### ISSUE THREAD

**Issue by khanium** [brantburnett/couchbasefakeit#44]
When I tried couchbasefakeit on a MacBook M2 gets the following message error:
`
[+] Running 3/0
 ✔ Network db_default                                                                                                                                       Created                                        0.0s 
 ✔ Container db-couchbase-1                                                                                                                                 Created                                        0.0s 
 ! couchbase The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                0.0s 
Attaching to db-couchbase-1
db-couchbase-1  | CB_VERSION=7.0.3
db-couchbase-1  | Initializing Couchbase Server 7.0.3...
db-couchbase-1  | Starting Couchbase Server -- Web UI available at http://<ip>:8091
db-couchbase-1  | and logs available in /opt/couchbase/var/lib/couchbase/logs
db-couchbase-1  | runtime: failed to create new OS thread (have 
db-couchbase-1  | 2 already; errno=22)
db-couchbase-1  | fatal error: newosproc
db-couchbase-1  | 
db-couchbase-1  | runtime stack:
db-couchbase-1  | 
db-couchbase-1  | runtime.throw(
db-couchbase-1  | 0x4d8d66, 0x9)
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/panic.go:596 +0x95
db-couchbase-1  | runtime.newosproc(0xc42002e000, 0xc42003e000)
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/os_linux.go:163
db-couchbase-1  |  +0x18c
db-couchbase-1  | runtime.newm(0x4df870, 0x0)
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/proc.go:1628 +0x137
db-couchbase-1  | runtime.main.func1()
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/proc.go:126 +0x36
db-couchbase-1  | runtime.systemstack(0x552700)
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/asm_amd64.s:327 +0x79
db-couchbase-1  | runtime.mstart()
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/proc.go:1132
db-couchbase-1  | 
db-couchbase-1  | 
db-couchbase-1  | goroutine 1 [running
db-couchbase-1  | ]:
db-couchbase-1  | runtime.systemstack_switch()
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/asm_amd64.s:281 fp=0xc42002a788 sp=0xc42002a780
db-couchbase-1  | runtime.main()
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/proc.go:127 +0x6c fp=0xc42002a7e0 sp=0xc42002a788
db-couchbase-1  | runtime.goexit()
db-couchbase-1  |       /home/couchbase/.cbdepscache/exploded/x86_64/go-1.8.5/go/src/runtime/asm_amd64.s:2197 +0x1
db-couchbase-1  |  fp=0xc42002a7e8 sp=0xc42002a7e0
`

**Comment by khanium** [comment]
Couchbase supports arm64 from version +7.1 . Running 7.2.2 I get similar error:
```
[+] Running 3/0
 ✔ Network db_default                                                                                                                                       Created                                        0.0s 
 ✔ Container db-couchbase-1                                                                                                                                 Created                                        0.0s 
 ! couchbase The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                0.0s 
Attaching to db-couchbase-1
db-couchbase-1  | CB_VERSION=7.2.2
db-couchbase-1  | Initializing Couchbase Server 7.2.2...
db-couchbase-1  | Starting Couchbase Server -- Web UI available at http://<ip>:8091
db-couchbase-1  | and logs available in /opt/couchbase/var/lib/couchbase/logs
db-couchbase-1  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
db-couchbase-1  | /opt/couchbase/bin/couchbase-server: line 166:   150 Segmentation fault      erl -noshell -setcookie nocookie -sname init -run init stop 2>&1 > /dev/null
db-couchbase-1  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
db-couchbase-1  | /opt/couchbase/bin/couchbase-server: line 166:   237 Segmentation fault      erl -noshell -setcookie nocookie -sname init -run init stop 2>&1 > /dev/null
db-couchbase-1  | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
db-couchbase-1  | /opt/couchbase/bin/couchbase-server: line 166:   324 Segmentation fault      erl -noshell -setcookie nocookie -sname init -run init stop 2>&1 > /dev/null

```

**Comment by brantburnett** [comment]
Unfortunately, this is going to be a bit difficult. One of the components used under the hood is the https://github.com/bentonam/fakeit library. This library isn't being maintained and still uses the NodeJS Couchbase SDK 2.x. This SDK in turn uses an older version of `libcouchbase` which doesn't appear to compile successfully on ARM64.

@bentonam Would you accept a PR updating to the latest Couchbase SDK for fakeit so that I don't need to fork?

**Comment by khanium** [comment]
Thanks @brantburnett, could we make this component optional? I really do not need to generate data yet. It could be done in a second phase, once the fakeit component is available for arm64 images

**Comment by brantburnett** [comment]
@khanium 

Sorry this has taken me a few days, it involved a few rabbit holes I had to go down. That said, I've released a new image here: https://hub.docker.com/repository/docker/btburnett3/couchbase-quickinit/general

This image has all of the features except for `fakeit` support, while also adding ARM64 images for 7.1 and 7.2 versions. The intention here is that it becomes the base image extended by `couchbasefakeit`. Having it in a separate image should help reduce confusion, rather than having different features on this image depending on platform.

Can you try this image out for me and see if it works for you? I don't yet have an Apple Silicon device to test this with.

**Comment by khanium** [comment]
No worries, thanks a lot for the effort. Unfortunately, I got the following error: 
`
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/scripts/configure-node.sh": permission denied: unknown.
`

**Comment by brantburnett** [comment]
@khanium 

Ahh, I knew I forgot something. Needed to set executable bits on the scripts since the build agent is building on Linux not Windows. Can you try pulling the latest image?
